# Generated by Django 3.1.7 on 2021-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='name',
            new_name='fname',
        ),
        migrations.AddField(
            model_name='buyer',
            name='lname',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
