# Generated by Django 3.1.7 on 2021-03-26 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20210326_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='fname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='lname',
        ),
    ]
