# Generated by Django 3.1.7 on 2021-04-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0007_kitchencategory'),
        ('mainApp', '0005_bakery_frozenfoods_pulses'),
    ]

    operations = [
    ]
