# Generated by Django 3.1.7 on 2021-04-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_beverages_snacks_spices'),
        ('mainApp', '0008_merge_20210405_1331'),
    ]

    operations = [
    ]
