# Generated by Django 3.1.7 on 2021-04-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_merge_20210405_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchencategory',
            name='bakery',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.bakery'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchencategory',
            name='frozen_foods',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.frozenfoods'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kitchencategory',
            name='pulses',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.pulses'),
            preserve_default=False,
        ),
    ]
