# Generated by Django 3.1.7 on 2021-04-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0011_auto_20210405_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchencategory',
            name='bakery',
        ),
        migrations.RemoveField(
            model_name='kitchencategory',
            name='frozen_foods',
        ),
        migrations.RemoveField(
            model_name='kitchencategory',
            name='fruits',
        ),
        migrations.RemoveField(
            model_name='kitchencategory',
            name='pulses',
        ),
        migrations.RemoveField(
            model_name='kitchencategory',
            name='vegetables',
        ),
        migrations.AddField(
            model_name='kitchencategory',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
