# Generated by Django 3.1.7 on 2021-04-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0012_auto_20210405_1453'),
        ('mainApp', '0012_auto_20210405_1457'),
    ]

    operations = [
    ]
