# Generated by Django 3.1.7 on 2021-04-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0013_merge_20210405_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='accountNumber',
            field=models.CharField(blank=True, default=None, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='bankName',
            field=models.CharField(blank=True, default=None, max_length=28, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='ifscCode',
            field=models.CharField(blank=True, default=None, max_length=28, null=True),
        ),
    ]
