# Generated by Django 3.1.7 on 2021-04-06 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0014_auto_20210406_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='ifscCode',
        ),
    ]
