# Generated by Django 3.1.7 on 2021-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0017_auto_20210406_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='spices',
            name='desc',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
