# Generated by Django 3.1.7 on 2021-04-12 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0019_auto_20210410_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bakery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.bakery')),
                ('Beverages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.beverages')),
                ('FrozenFoods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.frozenfoods')),
                ('Fruits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.fruits')),
                ('KitchenCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.kitchencategory')),
                ('Pulses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.pulses')),
                ('Snacks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.snacks')),
                ('Spices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.spices')),
                ('Vegetables', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.vegetables')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.buyer')),
            ],
        ),
    ]
