# Generated by Django 3.1.7 on 2021-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0020_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='frozenfoods',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='frozenfoods',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
