# Generated by Django 3.1.7 on 2021-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0021_auto_20210412_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='Bakery',
            new_name='bakery',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Beverages',
            new_name='beverages',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='FrozenFoods',
            new_name='frozenFoods',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Fruits',
            new_name='fruits',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='KitchenCategory',
            new_name='kitchenCategory',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Pulses',
            new_name='pulses',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Snacks',
            new_name='snacks',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Spices',
            new_name='spices',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='Vegetables',
            new_name='vegetables',
        ),
        migrations.AddField(
            model_name='bakery',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bakery',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='beverages',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='beverages',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='fruits',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pulses',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='pulses',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='snacks',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='spices',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='spices',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vegetables',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='vegetables',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
