# Generated by Django 3.1.7 on 2021-04-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0022_auto_20210412_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='kitchenCategory',
            new_name='cat',
        ),
    ]
