# Generated by Django 3.1.7 on 2021-04-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0028_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='address2',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='address1',
            field=models.CharField(max_length=50),
        ),
    ]
