# Generated by Django 3.1.7 on 2021-04-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0029_auto_20210415_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='notes',
        ),
    ]
