# Generated by Django 3.1.7 on 2021-04-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0034_ordersplaced'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='quan',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
