# Generated by Django 3.1.7 on 2021-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0036_auto_20210416_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruits',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
