# Generated by Django 3.1.7 on 2021-04-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0037_fruits_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='bakery',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='beverages',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frozenfoods',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pulses',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snacks',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='spices',
            name='stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vegetables',
            name='stock',
            field=models.BooleanField(default=False),
        ),
    ]
