# Generated by Django 3.1.7 on 2021-04-17 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0038_auto_20210416_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='address1',
            new_name='address',
        ),
    ]
