# Generated by Django 3.1.7 on 2021-04-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0039_auto_20210417_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='bakery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.bakery'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='beverages',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.beverages'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.kitchencategory'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='frozenFoods',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.frozenfoods'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='fruits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.fruits'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='pulses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.pulses'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='snacks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.snacks'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='spices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.spices'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='vegetables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.vegetables'),
        ),
    ]
