# Generated by Django 3.1.7 on 2021-04-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_auto_20210417_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simran',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
