# Generated by Django 3.1.7 on 2021-04-18 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0040_auto_20210417_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='seller_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersplaced',
            name='seller_details',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='frozenfoods',
            name='cat',
            field=models.CharField(default='Frozen Foods', max_length=20),
        ),
    ]
