# Generated by Django 3.1.7 on 2021-04-18 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0041_auto_20210418_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='seller_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
        ),
        migrations.AlterField(
            model_name='ordersplaced',
            name='seller_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
        ),
    ]
