# Generated by Django 3.1.7 on 2021-04-18 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0042_auto_20210418_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='seller_details',
        ),
        migrations.RemoveField(
            model_name='ordersplaced',
            name='seller_details',
        ),
    ]
