# Generated by Django 3.1.7 on 2021-04-18 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0043_auto_20210418_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersplaced',
            name='seller_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.seller'),
        ),
    ]
