# Generated by Django 3.1.7 on 2021-04-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0045_contact'),
        ('mainApp', '0041_simran'),
    ]

    operations = [
    ]
