# Generated by Django 3.1.7 on 2021-04-18 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0046_merge_20210418_2125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Simran',
        ),
    ]
